/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IMAGEALTER_H_RPCGEN
#define _IMAGEALTER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dataStruct {
	int len;
	u_char *data;
};
typedef struct dataStruct dataStruct;

#define IMAGEALTERPROG 0x2007001
#define IMAGEALTERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define IMAGEALTER 1
extern  dataStruct * imagealter_1(dataStruct *, CLIENT *);
extern  dataStruct * imagealter_1_svc(dataStruct *, struct svc_req *);
extern int imagealterprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IMAGEALTER 1
extern  dataStruct * imagealter_1();
extern  dataStruct * imagealter_1_svc();
extern int imagealterprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dataStruct (XDR *, dataStruct*);

#else /* K&R C */
extern bool_t xdr_dataStruct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IMAGEALTER_H_RPCGEN */
