/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "imageAlter.h"
#include "jpegUtil.h"

dataStruct *
imagealter_1_svc(dataStruct *argp, struct svc_req *rqstp)
{
	static dataStruct  result;

	jpegUtil::alterImage(&result);

	return &result;
}
