/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "imageAlter.h"

bool_t
xdr_dataStruct (XDR *xdrs, dataStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->len))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data, (uint*)&objp->len, objp->len))
		 return FALSE;
	return TRUE;
}
