/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "imageAlter.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

dataStruct *
imagealter_1(dataStruct *argp, CLIENT *clnt)
{
	static dataStruct clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, IMAGEALTER,
		(xdrproc_t) xdr_dataStruct, (caddr_t) argp,
		(xdrproc_t) xdr_dataStruct, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
