/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "imageAlter.h"

bool_t
xdr_dataStruct (XDR *xdrs, dataStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->len))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->data, (uint*)&objp->len, objp->len, sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}
